/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.yourspider.taxifarecalculator;

public class DistanceFinder {
	private RowElement[] rows;

 	public void setRows(RowElement[] rows) {
		this.rows = rows;
	}

	public RowElement[] getRows() {
		return rows;
	}

	private java.lang.String status;

 	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getStatus() {
		return status;
	}

	private java.lang.String[] destination_addresses;

 	public void setDestination_addresses(java.lang.String[] destination_addresses) {
		this.destination_addresses = destination_addresses;
	}

	public java.lang.String[] getDestination_addresses() {
		return destination_addresses;
	}

	private java.lang.String[] origin_addresses;

 	public void setOrigin_addresses(java.lang.String[] origin_addresses) {
		this.origin_addresses = origin_addresses;
	}

	public java.lang.String[] getOrigin_addresses() {
		return origin_addresses;
	}

}