/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.yourspider.taxifarecalculator;

public class Distance {
	private java.lang.Integer value;

 	public void setValue(java.lang.Integer value) {
		this.value = value;
	}

	public java.lang.Integer getValue() {
		return value;
	}

	private java.lang.String text;

 	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getText() {
		return text;
	}

}