/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.yourspider.taxifarecalculator;

public class ElementElement {
	private Distance distance;

 	public void setDistance(Distance distance) {
		this.distance = distance;
	}

	public Distance getDistance() {
		return distance;
	}

	private Duration duration;

 	public void setDuration(Duration duration) {
		this.duration = duration;
	}

	public Duration getDuration() {
		return duration;
	}

	private java.lang.String status;

 	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getStatus() {
		return status;
	}

}