/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.yourspider.taxifarecalculator;

public class RowElement {
	private ElementElement[] elements;

 	public void setElements(ElementElement[] elements) {
		this.elements = elements;
	}

	public ElementElement[] getElements() {
		return elements;
	}

}